### ISSUE TITLE
你好，请问一下你的dssp版本是不是只适用与martini2，martini3用不了

### ISSUE THREAD

**Issue by yxg618** [arantir123/MCGLPPI#1]
你好，请问一下你的dssp版本是不是只适用与martini2，martini3用不了

**Comment by arantir123** [comment]
您好，martini3 要用martinize programe生成：https://github.com/marrink-lab/vermouth-martinize

**Comment by yxg618** [comment]
> 您好，martini3使用martinize程序生成： https: [//github.com/marrink-lab/vermouth-martinize](https://github.com/marrink-lab/vermouth-martinize)

您好，是的。在运行martinize2时会报这样的错误。WARNING - DSSP-version - Vermouth is tested only with DSSP versions ('2.2.1', '3.0.0'). The provided DSSP (version 2.0.4) may result in inaccurate secondary structure ，请问一下您给的dssp文件是不是只适用与martini2。感谢您的回复。

**Comment by arantir123** [comment]
您好，是的。

**Comment by yxg618** [comment]
> 您好，是的。
您好，请问一下为什么您生成的itp文件中有蛋白质的序列，是细节没有具体描述吗？

**Comment by arantir123** [comment]
您好，对于MARTINI3我们调整为类似于MARTINI2的格式，MARTINI2生成的itp会有序列，MARTINI3的itp没有序列，所以我们为3也添加了。
