### ISSUE TITLE
关于使用martini3的问题

### ISSUE THREAD

**Issue by yxg618** [arantir123/MCGLPPI#2]
您好！在您创建create_cg_geo_params
/自述中，python py/m3_to_m2.py molecule_0.itp Protein_A.itp > molecule_0_M2.itp。在m3转换成m2时， molecule_0.itp是martinize2的生成文件， Protein_A.itp是martini.py的生成文件。是如果要使用martini3的话，martinize2，martini.py都要运行一次，并将生成的文件作为m3_to_m2.py 的输入，生成符合条件的itp文件吗？

**Comment by arantir123** [comment]
是的，生成M3的文件，martinize程序和martini.py都要运行一次，然后生成M3的Itp molecular.itp和M2的itp protein.itp
