### ISSUE TITLE
基于 AB-bind 数据集的 ddG 预测时报错'CG22_PackedProtein' object has no attribute 'intermol_mat'

### ISSUE THREAD

**Issue by 904301438** [arantir123/MCGLPPI#3]
![微信截图_20241219023113](https://github.com/user-attachments/assets/b9ce234e-246f-4a23-a4d4-6049d5fbaffd)

**Comment by arantir123** [comment]
您好，我现在服务器上不去，但是我用我的笔记本跑了一下没有问题，可以提供更多的信息嘛？我猜测原因来自于intermol是cg_steps_energy_injection
/cg_protein.py中蛋白质类的新attribute，在cg_steps/cg_protein.py中是没有的，您确认一下跑AB-bind的时候相关的代码用的是不是cg_steps_energy_injection路径下提供的那些。

**Comment by 904301438** [comment]
> 您好，我现在服务器上不去了，但是我用我的笔记本跑了一下没有问题，可以提供更多的信息吗？我猜测原因来自intermol是cg_steps_energy_injection /cg_ Protein.py中蛋白质类的新属性，在cg_steps/cg_ Protein.py中是没有的，您确认一下运行AB-bind的时候相关的代码用的是不是cg_steps_energy_injection路径下提供的那些。

您好，确实是cg_Protein.py中类的调用问题，现在我运行cg_steps_energy_injection/cg_downstream_1gpu_10CV_GBT.py时，他调用的是cg_steps/cg_ Protein.py中的pack函数，导致他无法打包这个属性。但是我检查了一些相关函数的头文件导入，并且怀疑是torchdrug中的_init_导入问题，将他们全部改为从cg_steps_energy_injection导入，结果仍然调用的是cg_steps中的函数。于是我又尝试简单将cg_steps_energy_injection中的pack函数替换到cg_steps的cg_ Protein.py文件中，但这又导致了pack中的num_residues类型为None的问题。值得注意的是，我并没有自己进行数据预处理与模型与训练，而是直接下载了您项目中提供的相关数据与预训练模型，直接运行的python cg_steps_energy_injection/cg_downstream_1gpu_10CV_GBT.py -c config/ppi_cg/cg_m1101_gearnet_gbt_WTtype.yaml。以及在初次运行时，出现cg_steps和cg_steps_energy_injection存在重复注册同名类的问题，我是通过直接将cg_steps中的注册给重命名来解决的这个问题，但我不确定这是否会导致我后续的问题。
感谢您的回复。

**Comment by arantir123** [comment]
您好，这里确实是这样的，torchdrug的导入逻辑如果不做底层的修改确实会出现您说的情况。对于现在AB-bind的实现，其实在实现时是基于了MCGLPPI-M2的一个扩展代码版本（但是基于上述运行命令和对应的运行脚本执行的话整个运行逻辑和论文中是一致的）。这里放在cg_steps_energy_injection路径中就是为了和cg_steps中的做区分（就是分别存储记录一下）。所以我的一个最简单的建议是目前可以clone一份新的独立代码，对于执行AB-bind，就把其中cg_steps_energy_injection直接覆盖掉cg_steps里面所有的文件就可以了。

**Comment by arantir123** [comment]
Note:
if you encounter the "'CG22_PackedProtein' object has no attribute 'intermol_mat'" error as above, here is an explanation:

For the current implementation for AB-bind predictions, it is actually based on an extended test version of the MCGLPPI-M2 code (in /cg_steps_energy_injection/). While the execution logic is consistent with the descriptions in the original manuscript when using the provided running commands and corresponding scripts.

To differentiate this extended version from the original version, the corresponding code are stored in /cg_steps_energy_injection/ and /cg_steps/ paths separately. A difference in "CG22_PackedProtein" class in /cg_steps_energy_injection/ has an additional attribute "intermol_mat". However, current underlying logic of TorchDrug would arise a calling mistake when such classes with the same/duplicate name in the same root path.

Therefore, a potential solution is to clone an extra copy of the code. For running AB-bind, you could simply replace all the files in /cg_steps/ with those from /cg_steps_energy_injection/ :)
